name: time_futebol_app
description: "Aplicativo para gerenciamento de time de futebol"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências do Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Gerenciamento de Estado
  provider: ^6.1.2

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Certifique-se de que sua pasta de assets está declarada aqui
  assets:
    - assets/images/