// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKH2NW1Z9m7aPQhatW-bK9mYWSssh0C3c',
    appId: '1:760190231979:web:f7cc28590ea0fcc55e9eee',
    messagingSenderId: '760190231979',
    projectId: 'app-time-futebol',
    authDomain: 'app-time-futebol.firebaseapp.com',
    storageBucket: 'app-time-futebol.firebasestorage.app',
    measurementId: 'G-BQ19EMMKHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dgPJhL9UAaHWl7ITu4AxnhTy9DszpAk',
    appId: '1:760190231979:android:99733ea1f9a8f5035e9eee',
    messagingSenderId: '760190231979',
    projectId: 'app-time-futebol',
    storageBucket: 'app-time-futebol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUsLJp1ycOJrUjiP-J0Z2ptyin8n2UHd0',
    appId: '1:760190231979:ios:1f8d26be63b3c4c35e9eee',
    messagingSenderId: '760190231979',
    projectId: 'app-time-futebol',
    storageBucket: 'app-time-futebol.firebasestorage.app',
    iosBundleId: 'com.example.timeFutebolApp',
  );
}
